[package]
name = "dinoscore"
version = "5.0.0"
authors = ["piegames <git@piegames.de>"]
edition = "2021"
default-run = "viewer"

# https://github.com/rust-lang/cargo/issues/9778
[[bin]]
name = "viewer"
path = "src/viewer/main.rs"

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[[bin]]
name = "cli"
path = "src/cli/main.rs"

[lib]
name = "dinoscore"
path = "src/lib.rs"

[profile.dev]
# strip = "symbols" # Not stable yet
lto = "off" # even less than 'false'

[profile.release]
# strip = "symbols" # Not stable yet
lto = true

[dependencies]

# GTK dependencies
libadwaita = { version = "0.9", features = [ "v1_7" ] }
gtk4 = { version = "0.11", features = [ "v4_14" ] }
glib = { version = "0.22", features = ["log", "v2_74"] }
gio = { version = "0.22", features = ["v2_74"] }
cairo-rs = { version = "0.22", features = ["png", "pdf", "svg", "v1_16"]}
poppler-rs = { version = "0.26", features = ["v20_9"] }
glycin = { version = "4.0.0-alpha.7", features = ["gdk4"] }
fast_image_resize = "5"

# Utility
atomicwrites = "0.4.0"
pipeline = { git = "https://github.com/piegamesde/pipeline.rs" }
git-version = "0.3.4"
itertools = "0.14.0"
noisy_float = "0.2.0"

# Utility containers
either = "1.6.0"
maybe-owned = { version = "0.3.4", features = ["serde"] }
typed-index-collections = { version = "3.0.3", features = [ "serde-std" ] }
fragile = "2.0"

# File format
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0"
derive_more = { version = "2", features = [ "full" ] }
zip = "8"
xdg = { git = "https://github.com/piegamesde/rust-xdg", branch = "windows" }
uuid = { version = "1.4", features = [ "v4", "serde" ] }
walkdir = "2"

# Xournal
flate2 = "1.0.20"
lenient_semver_parser = { version = "0.4.2", default-features = false }
lenient_version = { version = "0.4.2" }

# Async
futures = "0.3.5"
# For its `block_on`, which has different semantics w.r.t. reentrancy
futures-lite = "2"

# Crash and log
log = "0.4.14"
log-panics = { version = "2.0.0", features = [ "with-backtrace" ] }
fern = { git = "https://github.com/piegamesde/fern", features = [ "date-based", "colored" ]}
chrono = "0.4.19"
anyhow = "1.0.40"
backtrace = "0.3.60"

# Resource compilation
gvdb = { version = "0.10", features = [ "gresource" ] }
gvdb-macros = "0.1.4"

# Editor dependencies
blocking = { version = "1.0", optional = true }
image = { version = "0.25", features = ["png"], default-features = false, optional = true }
imageproc = { version = "0.27.0", optional = true }
attohttpc = { version = "0.29", features = ["multipart-form", "json"], optional = true }

# CLI dependencies
clap = { version = "3", features = ["cargo", "derive", "wrap_help"], optional = true }

[target.'cfg(unix)'.dependencies]
# Midi
midi-event = "0.2.0"
portmidi = "0.3"

# Unix-only
pyo3 = { version = "0.19", features = [ "auto-initialize", "anyhow", "abi3-py37", "generate-import-lib" ] }

[build-dependencies]
glib-build-tools = "0.22"
xdg = { git = "https://github.com/piegamesde/rust-xdg", branch = "windows" }

[dev-dependencies]
tempdir = "0.3.7"

[features]
default = ["viewer", "editor", "cli"]
viewer = []
editor = [
    "image",
    "imageproc",
    "attohttpc",
    "blocking",
]
cli = [
    "clap",
    "editor", # We still need to be able to do recognition
]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(test)'] }
