name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cache ~/.cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-test-shell-dotcargo
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-test-shell-build-target
      - name: Build in shell.nix
        run: nix-shell --pure --run "cargo build --all-targets --locked"

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        rust:
          #- 1.51.0 # MSRV
          - stable
          #- nightly
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup environment (hack on Cargo)
        run: |
          mkdir -p ~/.local/bin
          #cargo=$(which cargo)
          cargo="cargo"
          echo "#!/bin/env bash" >> ~/.local/bin/cargo
          echo 'cmd=$(echo "'$cargo' $@")' >> ~/.local/bin/cargo
          echo 'nix-shell --run "$cmd"' >> ~/.local/bin/cargo
          chmod +x ~/.local/bin/cargo
          cat ~/.local/bin/cargo
      - name: Cache ~/.cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-test-dotcargo-${{ matrix.rust }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-test-build-target-${{ matrix.rust }}
      - name: build --all-targets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
